# Las bibliotecas de iconos más comunes en aplicaciones Nuxt/Vue son:
# 1. Nuxt Icon (que soporta múltiples colecciones como Material Design Icons, Phosphor, etc.)
# 2. Vue Feather Icons
# 3. Iconify
# 4. Material Design Icons
# 5. Heroicons
# 6. Bootstrap Icons
# 7. Phosphor Icons
# 
# Los valores actuales que has aceptado ("user", "heart", "exclamation-triangle", etc.) 
# parecen ser nombres descriptivos simples que funcionan en varias de estas bibliotecas.
# Para confirmar cuál estás usando, puedes revisar el package.json o los componentes Icon en tu proyecto.

frontend:
  app_name: "zefiro"
  main_info: >
    Esta aplicación genera nuevas IAs de agentes o crew. Ejecutar esta aplicación te añadira una nueva crew en el desplegable de arriba a la derecha.

  download_example_report_link: "https://github.com/jaimevalero/zefiro/raw/main/meta-crew-frontend/static/examples/rancho-relax.md"
  # Nueva configuración de tema
  theme:
    dark: false
    colors:
      primary: "#673AB7"    # Púrpura, simboliza creatividad e innovación
      secondary: "#3F51B5"  # Azul profundo, confianza y profesionalismo
      accent: "#FFC107"     # Amarillo, energía y enfoque
      info: "#2196F3"       # Azul claro, claridad y comunicación
      warning: "#FF9800"    # Naranja, atención y dinamismo
      error: "#F44336"      # Rojo, errores y alertas
      alert: "#FFEB3B"      # Amarillo claro, advertencias suaves
      success: "#4CAF50"    # Verde, logros y éxito
  # Definición flexible de formularios
  form:
    title: "Información para Crear tu Nueva Crew"
    description: "Por favor proporciona los detalles para crear tu crew de IA especializada"
    fields:
      - name: "crew_purpose"
        label: "Propósito de la Crew"
        description: "¿Qué quieres que haga tu crew de IA? Describe el objetivo principal y las tareas clave."
        type: "textarea"
        required: true
        icon: "target"

      - name: "domain_industry"
        label: "Dominio o Industria"
        description: "¿En qué sector, industria o área de conocimiento se aplicará esta crew?"
        type: "textarea"
        required: true
        icon: "briefcase"

      - name: "target_users"
        label: "Usuarios Finales"
        description: "¿Quiénes utilizarán esta crew? Describe su perfil y necesidades específicas."
        type: "textarea"
        required: true
        icon: "users"
        
      - name: "human_agents"
        label: "Agentes Humanos Equivalentes"
        description: "¿Qué roles o especialistas humanos resolverían normalmente este tipo de problemas?"
        type: "textarea"
        required: true
        icon: "doctor"
        
                
      - name: "problem_description"
        label: "Problemas y Dudas Típicas"
        description: "Describe los problemas y dudas específicas que quieres que resuelva la tecnología."
        type: "textarea"
        required: true
        icon: "help-circle"
                
      - name: "expected_output"
        label: "Resultados Esperados"
        description: "¿Qué tipo de resultados o entregables debe proporcionar la crew? (informes, recomendaciones, etc.)"
        type: "textarea"
        required: true
        icon: "star"


      - name: "workflow_description"
        label: "Flujo de Trabajo"
        description: "Si tienes idea, describe cómo imaginas que debería ser el proceso de trabajo de la crew."
        type: "textarea"
        required: false
        icon: "arrow-right"
        
      - name: "technical_requirements"
        label: "Requisitos Técnicos"
        description: "¿Existen requisitos técnicos específicos o restricciones que la crew deba considerar?"
        type: "textarea"
        required: false
        icon: "ruler"
        
      - name: "existing_solutions"
        label: "Soluciones Existentes"
        description: "¿Conoces soluciones o enfoques existentes para este problema? ¿Qué te gusta o no te gusta de ellos?"
        type: "textarea"
        required: false
        icon: "lightbulb"
        
      - name: "additional_info"
        label: "Información Adicional"
        description: "Cualquier otra información relevante para la creación de tu crew."
        type: "textarea"
        required: false
        icon: "plus-circle"

backend:
  case:
    prompt: >
      Eres un equipo de especialistas en bienestar psicológico y salud mental cotidiana. 
      <case>{case}</case>

  nomination:
    method:
      type: all