# Global configuration for all apps
app_list:
  dr-casa: "App para asistencia médica especializada"
  hidalgos: "App para asistencia a personas de la tercera edad"
  rancho-relaxo: "App para bienestar mental y emocional"
  footnotes: "App para corredores y atletas"
  multilevel: "App para adaptaciones curriculares multinivel"
  