app_list:
  arch-scan: ai-powered software architecture analysis suite
  dr-casa: App para asistencia médica especializada
  footnotes: App para corredores y atletas
  hidalgos: App para asistencia a personas de la tercera edad
  multilevel: App para adaptaciones curriculares multinivel
  rancho-relaxo: App para bienestar mental y emocional
  riskfolio: tu asesor financiero cognitivo
  zefiro: App para la creación de sistemas multiagente
