backend:
  case:
    prompt: 'Eres un equipo de expertos financieros que analiza perfiles de inversión
      y genera recomendaciones personalizadas.  <case>{case}</case>'
  nomination:
    method:
      type: all

frontend:
  app_name: Financial Profiler Suite
  download_example_report_link: https://www.google.com
  form:
    title: "Perfil de Inversor"
    description: "Complete su información financiera para análisis personalizado"
    fields:
      - name: "personal_data"
        label: "Datos Personales"
        description: "Edad, situación familiar, profesión"
        type: "textarea"
        required: true
        icon: "user"

      - name: "financial_status"
        label: "Situación Financiera"
        description: "Ingresos anuales, ahorros, deudas"
        type: "textarea"
        required: true
        icon: "wallet"

      - name: "investment_horizon"
        label: "Horizonte Temporal"
        description: "Años previstos para la inversión"
        type: "textarea"
        required: true
        icon: "calendar"

      - name: "risk_tolerance"
        label: "Tolerancia al Riesgo"
        description: "Escala del 1 (conservador) al 7 (agresivo)"
        type: "textarea"
        required: true
        icon: "balance"

      - name: "current_portfolio"
        label: "Inversiones Actuales"
        description: "Detalle de activos financieros actuales"
        type: "textarea"
        required: false
        icon: "chart-line"

      - name: "tax_situation"
        label: "Situación Fiscal"
        description: "Tramo IRPF y fiscalidad especial"
        type: "textarea"
        required: false
        icon: "percent"

  main_info: >
    Esta aplicación analiza tu perfil de riesgo y genera recomendaciones de inversión personalizadas.
    Nuestro equipo incluye:
    - Especialista en Perfiles de Inversión
    - Analista de Productos Indexados
    - Experto en Plataformas de Inversión
    - Especialista en Activos No Indexados
    - Especialista Fiscal Español
    - Orquestador de Contenido Accesible

  theme:
    dark: false
    colors:
      primary: "#003F6D"      # Azul más oscuro - transmite mayor confianza y estabilidad
      secondary: "#1E7D46"    # Verde más profesional - representa crecimiento financiero
      accent: "#D4AF37"       # Dorado - asociado con riqueza e inversión
      info: "#17A2B8"         # Se mantiene el azul turquesa para información
      warning: "#FFC107"      # Se mantiene el amarillo para advertencias
      error: "#DC3545"        # Se mantiene el rojo para errores
      alert: "#FFE0B2"        # Se mantiene el amarillo claro para alertas
      success: "#28A745"      # Se mantiene el verde para éxito

meta:
  description: "tu asesor financiero cognitivo"
  name: "riskfolio"




