financial_profiler_assessment:
  agent: financial_profiler
  context: []
  description: 'Evaluar perfil de riesgo mediante cuestionario dinámico. 1. Analizar
    edad, ingresos y horizonte temporal 2. Clasificar tolerancia al riesgo en escala
    1-7 3. Validar consistencia de datos financieros básicos 4. Identificar objetivos
    de inversión prioritarios Todos los análisis deben considerar parámetros regulatorios
    ESMA.
    Para el case <case>{case}</case>
    '
  expected_output: Informe detallado del perfil de riesgo del usuario

investment_analyst_assessment:
  agent: investment_analyst
  context:
  - financial_profiler_assessment
  description: 'Seleccionar productos indexados adecuados. 1. Filtrar ETFs con TER
    ≤0.5% 2. Aplicar criterios de diversificación geográfica 3. Priorizar fondos accumulating
    para reinversión 4. Verificar historial de replicación del índice Incluir relación
    riesgo/rendimiento para cada opción. Considerar otros productos financieros.
    Para el case <case>{case}</case>
    '
  expected_output: Catálogo personalizado de ETFs y fondos indexados



broker_advisor_assessment:
  agent: broker_advisor
  context:
  - financial_profiler_assessment
  - investment_analyst_assessment
  description: 'Evaluar plataformas de inversión recomendadas. 1. Comparar comisiones
    de operación y custodia 2. Analizar herramientas de seguimiento fiscal 3. Verificar
    certificación CNMV y seguros 4. Evaluar soporte en español y UX móvil Priorizar
    brokers con demo interactiva para nuevos usuarios.
    Para el case <case>{case}</case>
    '
  expected_output: Ranking de brokers con análisis comparativo


multi_asset_selector_assessment:
  agent: multi_asset_selector
  context:
  - financial_profiler_assessment
  - investment_analyst_assessment
  description: >
    Evaluar productos de inversión complementarios a los ETFs, según perfil de riesgo. 
    1. Analizar idoneidad de acciones individuales (dividendos estables, blue-chip, bajo beta)
    2. Identificar bonos soberanos/corporativos adecuados según duración y rating crediticio
    3. Proponer REITs o fondos inmobiliarios no cotizados si el horizonte lo permite
    4. Evaluar productos garantizados o estructurados para perfiles conservadores
    5. Excluir productos con opacidad, liquidez baja o comisiones excesivas
    Considerar normativa MiFID II sobre idoneidad del producto al perfil.
    Para el case <case>{case}</case>
  expected_output: Recomendación de productos multiactivo no indexados, con justificación de compatibilidad según perfil


tax_consultant_assessment:
  agent: tax_consultant
  context:
  - broker_advisor_assessment
  - investment_analyst_assessment
  - multi_asset_selector_assessment
  description: 'Calcular implicaciones fiscales según normativa española. 1. Modelar
    retención de dividendos (19%) 2. Simular plusvalías para diferentes horizontes
    3. Incluir beneficios fiscales para planes pensiones 4. Generar checklist declaración
    Renta Adaptar ejemplos a modelo 100 formato simplificado.
    Para el case <case>{case}</case>
    '
  expected_output: Guía fiscal detallada con escenarios prácticos


report_orchestrator_assessment:
  agent: report_orchestrator
  context:
  - financial_profiler_assessment
  - investment_analyst_assessment  
  - tax_consultant_assessment
  - broker_advisor_assessment
  - multi_asset_selector_assessment
  description: 'Generar guía final integrada para principiantes. 1. Combinar recomendaciones
    técnicas en lenguaje sencillo 2. Crear roadmap de pasos para primera inversión
    3. Incluir capturas de ejemplo en plataforma seleccionada 4. Adjuntar resumen
    ejecutivo imprimible Verificar coherencia entre todas las secciones.
    Para el case <case>{case}</case>
    '
  expected_output: Documento completo con guía práctica ilustrada


